server {
    listen 80;
    server_name _;

    root /var/www/irremote;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # کش فایل‌های استاتیک
    location ~* \.(css|js|png|jpg|ico)$ {
        expires 1d;
        add_header Cache-Control "public";
    }

    # جلوگیری از دسترسی به فایل‌های مخفی
    location ~ /\. {
        deny all;
    }
}
